export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  tags?: string[];
  brand?: string;
  stock?: number;
  isNew?: boolean;
  isSale?: boolean;
};

export const products: Product[] = [
  {
    id: "notebook-1",
    name: "クラシックノート",
    description: "メモ、スケッチ、アイデアに最適なノートです。",
    price: 599,
    image: "https://c.imgz.jp/209/50262209/50262209b_417_d_500.jpg",
    category: "ノート",
    tags: ["ノート", "紙製品", "新商品"],
    brand: "ミリグラム",
    stock: 120,
    isNew: true,
  },
  {
    id: "pen-1",
    name: "スムースゲルペン",
    description: "鮮やかなインクでなめらかに書けます。",
    price: 249,
    image: "https://www.alotmall.com/cdn/shop/files/The-Best-Gel-Pen-Brand-Pack-Blue-Collection-2.jpg?v=1729143415",
    category: "ペン",
    tags: ["ペン", "ゲル", "人気"],
    brand: "パイロット",
    stock: 80,
    isSale: true,
  },
  {
    id: "highlighter-1",
    name: "パステル蛍光ペン",
    description: "スタイリッシュに色分けできます。",
    price: 199,
    image: "https://m.media-amazon.com/images/I/71z5i0TlNqL._UF1000,1000_QL80_.jpg",
    category: "蛍光ペン",
    tags: ["蛍光ペン", "パステル", "新商品"],
    brand: "ゼブラ",
    stock: 60,
    isNew: true,
  },
  {
    id: "planner-1",
    name: "2025年デイリープランナー",
    description: "一年間の予定をおしゃれに管理。",
    price: 1299,
    image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRWOV2NomDnkOEqOHKAPfkPKeJqsHc6Ssn-KklL7vGbKUyTcsVHghpzaZi8yfoeITwJega7HeGh06eBIXlNHG8d-rKNh0pZ3d-6vz6cdmjilfS35uJc7X64",
    category: "手帳",
    tags: ["手帳", "プランナー", "新商品"],
    brand: "コクヨ",
    stock: 150,
    isNew: true,
  },
  {
    id: "marker-1",
    name: "油性マーカーセット",
    description: "あらゆるプロジェクトに最適な鮮やかな色。",
    price: 799,
    image: "https://item.shachihata.co.jp/catalog/images/products/00067900_pk.jpg",
    category: "アート用品",
    tags: ["マーカー", "アート", "人気"],
    brand: "ステッドラー",
    stock: 70,
    isSale: true,
  },
  {
    id: "deskset-1",
    name: "デスクオーガナイザーセット",
    description: "デスク周りをすっきり整理。",
    price: 1599,
    image: "https://www.ikea.com/jp/ja/images/products/kuggis-desk-organiser-set-2-pieces-grey-beige-dark-grey-beige__1294252_pe935393_s5.jpg?f=xl",
    category: "デスクアクセサリー",
    tags: ["デスク", "整理整頓", "新商品"],
    brand: "サンワサプライ",
    stock: 90,
    isNew: true,
  },
  // New products
  {
    id: "eraser-1",
    name: "高品質消しゴム",
    description: "きれいに消せるソフトな消しゴム。",
    price: 99,
    image: "https://www.forest.co.jp/forest/goods/images/p/508941.jpg",
    category: "消しゴム",
    tags: ["消しゴム", "文房具", "人気"],
    brand: "トンボ",
    stock: 200,
    isSale: true,
  },
  {
    id: "scissors-1",
    name: "カラフルはさみ",
    description: "安全で使いやすいカラフルなはさみ。",
    price: 399,
    image: "https://jp.images-monotaro.com/Monotaro3/pi/full/mono53751715-200923-02.jpg",
    category: "はさみ",
    tags: ["はさみ", "カラフル", "新商品"],
    brand: "ハサミ工房",
    stock: 110,
    isNew: true,
  },
  {
    id: "ruler-1",
    name: "透明定規30cm",
    description: "見やすくて丈夫な30cm定規。",
    price: 199,
    image: "https://tshop.r10s.jp/b-town/cabinet/01222500/35-1310-03.jpg?fitin=720%3A720",
    category: "定規",
    tags: ["定規", "透明", "人気"],
    brand: "ミリペン",
    stock: 130,
    isSale: true,
  },
  {
    id: "sticky-1",
    name: "カラフル付箋セット",
    description: "メモやマークに便利な付箋セット。",
    price: 299,
    image: "https://www.shop-stationery.com/html/upload/save_image/img_MCFC061_m2.jpg?1",
    category: "付箋",
    tags: ["付箋", "カラフル", "新商品"],
    brand: "ポストイット",
    stock: 160,
    isNew: true,
  },
  {
    id: "folder-1",
    name: "A4クリアファイル",
    description: "書類整理に便利なA4サイズのクリアファイル。",
    price: 149,
    image: "https://cdn.askul.co.jp/img/product/3L1/8470738_3L1.jpg",
    category: "ファイル",
    tags: ["クリアファイル", "A4", "人気"],
    brand: "コクヨ",
    stock: 180,
    isSale: true,
  },
  {
    id: "tape-1",
    name: "マスキングテープセット",
    description: "デコレーションやラッピングに最適。",
    price: 399,
    image: "https://jp.images-monotaro.com/Monotaro3/pi/full/mono14985470-230216-02.jpg",
    category: "テープ",
    tags: ["マスキングテープ", "デコレーション", "新商品"],
    brand: "mt",
    stock: 140,
    isNew: true,
  },
  {
    id: "pencil-1",
    name: "HB鉛筆 12本セット",
    description: "書きやすく折れにくい高品質鉛筆。",
    price: 399,
    image: "https://m.media-amazon.com/images/I/719kgyUV0QL.jpg",
    category: "鉛筆",
    tags: ["鉛筆", "HB", "人気"],
    brand: "ぺんてる",
    stock: 200,
    isSale: true,
  },
  {
    id: "mechanical-1",
    name: "シャープペンシル",
    description: "細かい作業に最適な0.5mmシャープペン。",
    price: 499,
    image: "https://cdn.askul.co.jp/img/product/3L1/652574_3L1.jpg",
    category: "シャープペンシル",
    tags: ["シャープペンシル", "機械式", "新商品"],
    brand: "ゼブラ",
    stock: 90,
    isNew: true,
  },
  {
    id: "brush-1",
    name: "水彩画用ブラシセット",
    description: "アートやイラストに最適なブラシセット。",
    price: 899,
    image: "https://m.media-amazon.com/images/I/61VgNa4J+mL._AC_UF894,1000_QL80_.jpg",
    category: "画材",
    tags: ["ブラシ", "水彩画", "人気"],
    brand: "ターレンス",
    stock: 75,
    isSale: true,
  },
  {
    id: "paint-1",
    name: "水彩絵の具12色セット",
    description: "発色が美しい水彩絵の具セット。",
    price: 1299,
    image: "https://www.craypas.co.jp/assets/product/146167.jpg",
    category: "画材",
    tags: ["絵の具", "水彩", "新商品"],
    brand: "ホルベイン",
    stock: 50,
    isNew: true,
  },
  {
    id: "calendar-1",
    name: "2025年卓上カレンダー",
    description: "デスクにぴったりのシンプルなカレンダー。",
    price: 499,
    image: "https://www.hansoku-style.jp/html/upload/save_image/KH-V010057-06.png",
    category: "カレンダー",
    tags: ["カレンダー", "卓上", "人気"],
    brand: "ナカバヤシ",
    stock: 130,
    isSale: true,
  },
  {
    id: "envelope-1",
    name: "カラフル封筒セット",
    description: "手紙や書類に使えるカラフルな封筒。",
    price: 299,
    image: "https://jp.images-monotaro.com/Monotaro3/pi/full/mono56682018-220302-02.jpg",
    category: "封筒",
    tags: ["封筒", "カラフル", "新商品"],
    brand: "セーラー",
    stock: 160,
    isNew: true,
  },
  {
    id: "stapler-1",
    name: "ミニホッチキス",
    description: "持ち運びに便利なコンパクトサイズ。",
    price: 349,
    image: "https://www.lihit-lab.com/wp-content/themes/lihit-lab/assets/import_img/main/M-20.jpg",
    category: "ホッチキス",
    tags: ["ホッチキス", "ミニ", "人気"],
    brand: "マックス",
    stock: 140,
    isSale: true,
  },
  {
    id: "clip-1",
    name: "ペーパークリップセット",
    description: "書類整理に便利なカラフルクリップ。",
    price: 149,
    image: "https://tshop.r10s.jp/nikkori/cabinet/onesell148/sa49e2b1f13c.jpg?fitin=720%3A720",
    category: "クリップ",
    tags: ["クリップ", "ペーパークリップ", "新商品"],
    brand: "コクヨ",
    stock: 200,
    isNew: true,
  },
  {
    id: "case-1",
    name: "ペンケース",
    description: "大容量で使いやすいペンケース。",
    price: 799,
    image: "https://www.kokuyo-shop.jp/sc/images/products/4901480398228_02.JPG",
    category: "ペンケース",
    tags: ["ペンケース", "大容量", "人気"],
    brand: "オート",
    stock: 90,
    isSale: true,
  },
  {
    id: "bag-1",
    name: "トートバッグ（文房具柄）",
    description: "おしゃれな文房具柄のトートバッグ。",
    price: 1599,
    image: "https://c.p02.c4a.im/images/item/14041038/e34a37beffdd923af89f2d58cc44f885e57298e06306772af95267003e9cd1c1?d=500x500",
    category: "バッグ",
    tags: ["トートバッグ", "文房具柄", "新商品"],
    brand: "リヒトラブ",
    stock: 80,
    isNew: true,
  },
  {
    id: "glue-1",
    name: "スティックのり",
    description: "しっかり貼れるスティックタイプののり。",
    price: 99,
    image: "https://www.yamato.co.jp/wp/wp-content/uploads/2024/08/YS-22-1024x1024.jpg",
    category: "のり",
    tags: ["のり", "スティックのり", "人気"],
    brand: "アラビック",
    stock: 200,
    isSale: true,
  },
  {
    id: "whiteboard-1",
    name: "ホワイトボード（A4サイズ）",
    description: "会議や勉強に便利なA4ホワイトボード。",
    price: 1299,
    image: "https://jp.images-monotaro.com/Monotaro3/pi/full/mono44795364-190702-02.jpg",
    category: "ホワイトボード",
    tags: ["ホワイトボード", "A4サイズ", "新商品"],
    brand: "コクヨ",
    stock: 70,
    isNew: true,
  },
  {
    id: "memo-1",
    name: "メモパッド",
    description: "持ち運びに便利なコンパクトメモ。",
    price: 199,
    image: "https://image1.shopserve.jp/midori-store.net/pic-labo/llimg/91803806_5.jpg?t=20210127095600",
    category: "メモ",
    tags: ["メモ", "パッド", "人気"],
    brand: "ミドリ",
    stock: 150,
    isSale: true,
  },
  {
    id: "sharpener-1",
    name: "鉛筆削り",
    description: "手軽に使えるコンパクト鉛筆削り。",
    price: 149,
    image: "https://www.tombow.com/files/2012/12/w_sharpener_item_04.jpg",
    category: "鉛筆削り",
    tags: ["鉛筆削り", "コンパクト", "新商品"],
    brand: "トンボ",
    stock: 180,
    isNew: true,
  },
  {
    id: "pencil-2",
    name: "JETSTREAM",
    description: "なめらかな書き心地と高級感を兼ね備えた、ジェットストリームの最上位モデル。ビジネスシーンやギフトに最適です。",
    price:  3300,
    image: "https://www.nichima.co.jp/data/photo/new_item/1044519267.jpg",
    category: "筆記具",
    tags: ["ボールペン", "高級", "新商品", "滑らか", "多機能"],
    brand: "三菱鉛筆",
    stock: 45,
    isNew: true,
  },
];
